name: Release
on:
  release:
    types:
      - published
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.x

      - name: Install build dependencies
        run: sudo apt-get -y install p7zip-full

      - name: Build
        run: ./scripts/build.sh

      - name: Upload release archive
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*
          asset_content_type: application/octet-stream
